#!/bin/bash
docker run \
    -p 4560:4560 \
    -e "EJABBERD_REGISTER_TRUSTED_NETWORK_ONLY=true" \
    -e "EJABBERD_ADMIN=${PYEJABBERD_TESTS_USERNAME}@${PYEJABBERD_TESTS_XMPP_DOMAIN}" \
    -e "EJABBERD_ADMIN_PWD=${PYEJABBERD_TESTS_PASSWORD}" \
    -e "XMPP_DOMAIN=${PYEJABBERD_TESTS_XMPP_DOMAIN}" \
    -e "EJABBERD_MUC_CREATE_ADMIN_ONLY=true" \
    -e "EJABBERD_REGISTER_ADMIN_ONLY=true" \
    -e "EJABBERD_MOD_ADMIN_EXTRA=true" \
    -e "EJABBERD_MOD_MUC_ADMIN=true" \
    dirkmoors/ejabberd
